### PR TITLE
Add v0.5 samples

### PR DESCRIPTION
**Pull request by will-moore**
Added a selection of the IDR samples from the ome2024-ngff-challenge.

cc @joshmoore

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @will-moore! (and cc: @normanrz). I'd suggest though that we copy these to the appropriate `/0.5/` directory to match the other sample data. Let me know if you need me to do that.

**Comment by will-moore** [comment]
Yes please!

**Comment by joshmoore** [comment]
Copy in progress. Pushed a commit.

**Comment by joshmoore** [comment]
Could something easily test these URLs and mark the PR red if they don't pass?

cc: @kbab

**Comment by will-moore** [comment]
I've just checked all those URLs in ome-ngff-validator and vizarr and all are good, thanks!

**Comment by joshmoore** [comment]
Heh. Fair & thanks! Automation next ;)

**Pull request merged**
