### PR TITLE
Add link to validate

### PR DESCRIPTION
**Pull request by will-moore**
Deployed at https://will-moore.github.io/ome-ngff-samples/

Experimental (for discussion)...

This adds a link to an experimental OME-NGFF validation page: E.g. https://ome-ngff-validator.netlify.app/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/9836842.zarr
See repo at https://github.com/will-moore/ome-ngff-validator

Several ideas / thoughts
 - Validation: It's nice to give users a way to check that the examples are valid JSON. The page above also allows users to validate against samples hosted elsewhere, with a link that can be shared etc. Useful when discussing/debugging external samples.
 - Metadata: That side loads and displays the root `.zattrs` JSON and the `.zarray` JSON for each path/array in the pyramid, which is useful to know when inspecting an OME-NGFF sample (and hard to check without other tools). I also thought about adding a "Metadata" button to the `ome-ngff-samples` table that would at least show the multiscales pyramid shapes, dtype, etc - but this is now handled by this separate page
 - Thumbnails: The page above uses `zarr.js` to load pixel data (for images below 512 x 512) and uses manual code to render that to canvas (doesn't use `viv/vizarr` or `react` to save on dependencies - and to try and keep it simpler). We could use that code to generate thumbnails on the https://idr.github.io/ome-ngff-samples/ page itself?

### CODE REVIEW

**Comment by joshmoore** [comment]
Discussed with @will-moore. Generally, :100:. Points we discussed:

- There is an issue in the UI when screens get quite wide.
- Also, the UI is getting a bit crowd with non-searchable columns. Perhaps all of them could be put behind an "Action" button? (Could the same action menu also pop up when you click on the image?)
- We should likely move the deployment netlify to gh pages (following https://github.com/hms-dbmi/vizarr/blob/main/.github/workflows/build_and_deploy.yml)
- Add support for plates (slightly blocked by the label issue: https://github.com/ome/omero-cli-zarr/issues/115)

Likely the only ones to think about before merging are the repo deployment and perhaps the action button.

cc: @manzt perhaps another button ("validate") for vizarr? :smile:

**Comment by joshmoore** [comment]
- I like the copy wiggling!
- Drop the "open in vizarr" and the "View in IDR" column bits to save some horizontal space?

**Comment by will-moore** [comment]
@joshmoore I removed the "View in IDR" column and added a link to the "Study" column. Also removed "Open in Vizarr text".

**Review by joshmoore — APPROVED** [review]
Thanks! From my POV, this is a big improvement and can be merged. I can imagine a re-ordering of the columns and a few things like that, but they are outwith this PR.

**Pull request merged**
