### PR TITLE
Add copy-to-clipboard button for s3 urls

### PR DESCRIPTION
**Pull request by will-moore**
Applying changes from https://github.com/ome/www.openmicroscopy.org/pull/564/ to here to add a copy button.

But, I haven't managed to test locally due to not having Jekyll installed.

https://utpalkumar.medium.com/how-to-install-jekyll-on-apple-m1-macbook-c87894b7fc70 looks painful.

So I tried https://anaconda.org/conda-forge/rb-jekyll ...

```
conda create --name jekyll
conda activate jekyll
conda install -c conda-forge rb-jekyll
cd Desktop/IDR/ome-ngff-samples/
jekyll Gemfile     # failed
gem install kramdown
jekyll Gemfile
"The git source git://github.com/jekyll/minima.git is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)"

bundle install
Git error: command `git clone 'git://github.com/jekyll/minima.git'
"/Users/wmoore/opt/anaconda3/envs/jekyll/lib/ruby/gems/2.6.0/cache/bundler/git/minima-fb70e785e8f77ebad3d6dcf03ba0925ecdb47b21" --bare --no-hardlinks --quiet` in directory
/Users/wmoore/Desktop/IDR/ome-ngff-samples has failed.
```

### CODE REVIEW

**Comment by sbesson** [comment]
Unfortunately, I am encountering similar issues as yours setting up a working Jekyll environment on my M1 laptop. Attempts to either use a conda environment or a Docker workflow e.g. similar to https://github.com/ome/www.openmicroscopy.org/blob/master/docker_startup.sh have also been unsuccessful.

This is made even more complex by the compatibility matrix betwee Ruby versions, Jekyll versions and github-pages versions. For instance the github-pages Gem does not support Jekyll 4.0 see https://github.com/github/pages-gem/issues/651 so I fail to understand how the Pages deployment currently builds with https://github.com/IDR/ome-ngff-samples/blob/2f501032b17cfac3923856741439a39c04a207d0/Gemfile#L15-L20
 @joshmoore do you have ideas or a working configuration?

**Comment by joshmoore** [comment]
Not on m1 _per se_. What I've done elsewhere when running into issues (and there are several at the moment since Jekyll is just at that critical breaking 4.x stage):

```
conda create -n env -c conda-forge rb-bundler c-compiler compilers cxx-compiler
conda activate env
bundle install
bundle exec jekyll serve
```

**Comment by will-moore** [comment]
Thanks @joshmoore
That seemed to create the env OK, but fails at:
```
$ bundle install
Fetching https://github.com/jekyll/minima.git
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    github-pages was resolved to 1, which depends on
      Ruby (~> 1.9.3)

    jekyll (~> 4.0) was resolved to 4.2.2, which depends on
      Ruby (>= 2.4.0)

Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 4.0)

    github-pages was resolved to 6, which depends on
      jekyll (= 1.2.1)

Bundler could not find compatible versions for gem "minima":
  In Gemfile:
    minima

    github-pages was resolved to 94, which depends on
      minima (= 1.0.1)
```

**Comment by will-moore** [comment]
Ah, looking in the `Gemfile` I see
```
gem "jekyll", "~> 4.0"
gem "minima", github: "jekyll/minima"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins
```
So I commented out that last line...
Looks happier so far, installing...

**Comment by sbesson** [comment]
This matches the implementation used for https://www.openmicroscopy.org/2021/12/16/ome-ngff.html. Unfortunately, my Jekyll environment is completely non-functional so I am unable to validate it locally. I'll try to get it sorted this week but it might be more efficient to have someone else to review it. A more involved solution would be to start having a merge job for this PR and deploy the staging version e.g. at https://snoopycrimecop.github.io/ome-ngff-samples

One potential RFE: since the link is part of an existing column, could we see replacing the text by a permissively licensed copy-to-clipboard icon?

**Review by joshmoore — APPROVED** [review]
Using my fork (by pushing to https://joshmoore.github.io/idr-ome-ngff-samples/), :+1:

Screen Shot 2022-05-23 at 11 08 37

(The only thing I noticed was that "copied" was shown fairly briefly, at least in terms of trying to get a screenshot :wink:)

**Review by sbesson — APPROVED** [review]

**Pull request merged**
